### ISSUE TITLE
Unknown event

### ISSUE THREAD

**Issue by dft111** [michgz/ac7maker#5] opened 2023-06-08 07:56 UTC
Hi, excellent work!
I get these errors when I try ac7maker. What could it be? Thank you!
I have a CT-X3000.

ac7maker-1.1.0 python ac7maker.py CaGaze/cagaze.json > CaGaze.AC7
Traceback (most recent call last):
  File "/mnt/HDD-120/DownloadsHDD/ac7maker-1.1.0/ac7maker.py", line 885, in <module>
    sys.stdout.buffer.write(ac7maker(b))
                            ^^^^^^^^^^^
  File "/mnt/HDD-120/DownloadsHDD/ac7maker-1.1.0/ac7maker.py", line 707, in ac7maker
    mdata = internal.midifiles.midifile_read(f3.read())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/HDD-120/DownloadsHDD/ac7maker-1.1.0/internal/midifiles.py", line 153, in midifile_read
    trk = process_track(b[pos+8:pos+8+x], division)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/HDD-120/DownloadsHDD/ac7maker-1.1.0/internal/midifiles.py", line 122, in process_track
    (d, pos) = consume_midi_event(b, pos)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/HDD-120/DownloadsHDD/ac7maker-1.1.0/internal/midifiles.py", line 109, in consume_midi_event
    raise Exception("Unknown event {0:02X}".format(evt))
Exception: Unknown event 33

**Comment by michgz** [comment] 2023-06-08 18:34
Thanks for your comments. I think the problem is caused my MIDI "running status", which is fixed in the latest version of ac7maker. Try downloading the "master" rather than "1.1.0".

**Comment by dft111** [comment] 2023-06-08 19:03
Hi, Thanks for the reply!
this is ac7maker-master result....

ac7maker-master python3 ac7maker.py CaGaze/cagaze.json > CaGaze.AC7
Traceback (most recent call last):
  File "/mnt/HDD-120/DownloadsHDD/ac7maker-master/ac7maker.py", line 900, in <module>
    sys.stdout.buffer.write(ac7maker(b))
                            ^^^^^^^^^^^
  File "/mnt/HDD-120/DownloadsHDD/ac7maker-master/ac7maker.py", line 765, in ac7maker
    mixers.append(ac7make_mixer_element(pt, b))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/HDD-120/DownloadsHDD/ac7maker-master/ac7maker.py", line 208, in ac7make_mixer_element
    g += struct.pack('B', pt_patch)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: ubyte format requires 0 <= number <= 255

**Comment by michgz** [comment] 2023-06-09 17:34
Would you mind copying your "cagaze.json" here? It seems to be something with the patch & bank definitions.

See here for an example: https://github.com/michgz/ac7maker/blob/master/examples/example-1.json     

Each of the 8 parts can have a "patch" and a "bank_msb" specified. Each of them should be a number in range 0-127. A lot of MIDI editors used the range 1-128, so you should subtract 1 in that case.

**Comment by dft111** [comment] 2023-06-09 18:09
Thanks, I managed to output the AC7 file.
Indeed, I deciphered the problem message, read line by line, and changed the "patch" number between 0-127 in json file.
Thank you, now I will try it in CT-X.
All the best!

**Comment by michgz** [comment] 2023-06-10 09:29
Great! Consider sharing rhythms that you create at casiomusicforums.com for others to enjoy

**Comment by dft111** [comment] 2023-06-10 10:48
Of course, let me get there!  Thank you!

**Closed as completed** 2023-06-15 19:49 UTC
